quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET,POST
quarkus.http.cors.origins=${CORS_ALLOWED_ORIGINS}
%dev.quarkus.http.cors.origins=https://localhost:4200

taskito.tasks.file.location=${TASKS_FILE_LOCATION}
%dev.taskito.tasks.file.location=./src/main/resources/tasks.json