quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET,POST,PUT
quarkus.http.cors.origins=${CORS_ALLOWED_ORIGINS}
%dev.quarkus.http.cors.origins=http://localhost:4200

quarkus.log.level=INFO
%dev.quarkus.log.level=FINEST

quarkus.http.access-log.enabled=true

taskito.tasks.file.location=${TASKS_FILE_LOCATION}
%dev.taskito.tasks.file.location=./src/main/resources/tasks.json